### ISSUE TITLE
Don't work 

### ISSUE THREAD

**Issue by batashi** [alfanak/belnder_arabic_text2#1]
Thanks you a lot of for this work 

I have try it on Fedora 29 , Blender Beta 2.8

i have this result 
![image](https://user-images.githubusercontent.com/6708191/56084197-927b9000-5e40-11e9-8d28-ce57b16b4825.png)

**Comment by alfanak** [comment]
You have to activate the Add-on after installing it using the they keys CTRL+F1 or by executing the operator "Write Arabic Text".

**Comment by batashi** [comment]
أشكرك 

Thanks you. 
yes it's work after mark addon from preference UI 
![image](https://user-images.githubusercontent.com/6708191/56154813-80c5f400-5fca-11e9-99f0-bc19ce954a75.png)

**Comment by alfanak** [comment]
العفو
